<?php
/**
 * Shows Picasa Web Albums on a page
 */

/**
 * Implementation of hook_menu().
 */
function vih_pwi_menu() {
    $items = array();
    $items['billedgalleri'] = array(
        'title' => 'Højdepunkter',
        'page callback' => 'vih_pwi_view',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu'
    );
    return $items;
}

/**
 * Implementation of hook_views_api().
 */
function vih_pwi_view() {
    drupal_add_css(drupal_get_path('module', 'vih_pwi') . '/jquery.pwi/css/pwi.css');
    drupal_add_js(drupal_get_path('module', 'vih_pwi') . '/jquery.pwi/js/jquery-1.4.2.min.js');
    drupal_add_js(drupal_get_path('module', 'vih_pwi') . '/jquery.pwi/js/jquery.slimbox2/jquery.slimbox2.js');
    drupal_add_js(drupal_get_path('module', 'vih_pwi') . '/jquery.pwi/js/jquery.blockUI.js');
    drupal_add_js(drupal_get_path('module', 'vih_pwi') . '/jquery.pwi/js/jquery.pwi.js');
    return '<script type="text/javascript">
		    $(document).ready(function() {

		        $("#picasaweb").pwi({
		            username: \'vejleih\',
					 maxResults: 5,
					 showAlbumDescription: false,
					 showPhotoCaption: true,
					 photoCaptionLength: 5,
					 showPhotoCaptionDate: true,
					 thumbSize: 160,
				     labels: {photo:"billede",	//-- override labels, to translate into your required language
					          photos: "billeder",
							  albums: "Tilbage til albums",
							  slideshow: "Vis slideshow",
							  loading: "Henter billeder...",
							  page: "Side",
						      prev: "Forrige",
							  next: "Næste",
							  devider: "|"
					},
					months: ["Januar","Februar","Marts","April","Maj","Juni","Juli","August","September","Oktober","November","December"]
		        });
		    });
		</script><div id="picasaweb"></div>';
}
