<?php
/**
 * Shows Picasa Web Albums on a page
 */

/**
 * Implements hook_help().
 */
function vih_pwi_help($path, $arg) {
  switch ($path) {
    case 'admin/help#vih_pwi':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('PWI embeds Picasa Webalbum on your site') .'</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Usage') . '</dt>';
      $output .= '<dd>' . t('To embed the slideshow, all you need to do is enable the module and configure it at <a href="@pwi">Scribd Input Filter</a>.', array('@pwi' => 'admin/settings/pwi')) . '.</dd>';
      $output .= '</dl>';
      return $output;
    case 'admin/settings/pwi':
      $output = t('Configure your PWI implementation of Picasa Webalbums');
      return $output;
  }
}

/**
 * Implementation of hook_menu().
 */
function vih_pwi_menu() {
    $items = array();
    $items['admin/settings/pwi'] = array(
        'title' => 'PWI',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('vih_pwi_admin_form'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM
    );
    return $items;
}

function vih_pwi_admin_form($form, &$form_state){
  $form['picasa_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Picasa User'),
    '#required' => true,
    '#default_value' => variable_get('picasa_user'),
  ); 
  // saves and executes a submission callback, see $form["#submit"] for that
  $form['save'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#executes_submit_callback' => true
  );
  $form['#submit'] = array(
    'vih_pwi_admin_form_submit'
  );
  return $form;
}

function vih_pwi_admin_validate($form, &$form_state) {  
  $form['picasa_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Picasa User'),
    '#required' => true,
    '#default_value' => variable_get('picasa_user'),
  ); 
}

function vih_pwi_admin_form_submit($form, &$form_state) {
  variable_set('picasa_user', $form_state['values']['picasa_user']);
  drupal_set_message(t("Values has been set"));
}

function vih_pwi_block_info() {
  // This example comes from node.module.
  $blocks['vih_pwi'] = array(
    'info' => t('Picasa Webalbums'), 
    // DRUPAL_CACHE_PER_ROLE will be assumed.
  );

  return $blocks;
}

function vih_pwi_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'vih_pwi':
      $block['subject'] = '';
      $block['content'] = vih_pwi_view();
      break;
  }
  return $block;
}

function vih_pwi_block_configure($delta = '') {
  // This example comes from node.module.
  $form = array();
  if ($delta == 'vih_pwi') {
    $form['picasa_user'] = array(
      '#type' => 'textfield',
      '#title' => t('Picasa User'),
      '#required' => true,
      '#default_value' => variable_get('picasa_user'),
    ); 
  }
  return $form;
}

function vih_pwi_block_save($delta = '', $edit = array()) {
  // This example comes from node.module.
  if ($delta == 'vih_pwi') {
    variable_set('picasa_user', $edit['picasa_user']);
  }
}

/**
 * Implementation of hook_views_api().
 */
function vih_pwi_view() {
    drupal_add_css(drupal_get_path('module', 'vih_pwi') . '/jquery.pwi/css/pwi.css');
    drupal_add_css(drupal_get_path('module', 'vih_pwi') . '/jquery.pwi/js/jquery.slimbox2/jquery.slimbox2.css');
    drupal_add_js(drupal_get_path('module', 'vih_pwi') . '/jquery.pwi/js/jquery.slimbox2/jquery.slimbox2.js');
    drupal_add_js(drupal_get_path('module', 'vih_pwi') . '/jquery.pwi/js/jquery.pwi.js');
    drupal_add_js('
(function ($) {
    $(document).ready(function() {
        $("#picasaweb").pwi({
		    username: \''.check_plain(variable_get('picasa_user')).'\',
            maxResults: 12,
            showAlbumDescription: false,
            showPhotoCaption: false,
            photoCaptionLength: 5,
            thumbSize: 170,
            thumbCrop: 1,
            showPhotoDate: false,
            labels: {photo:"billede",	//-- override labels, to translate into your required language
                     photos: "billeder",
                     albums: "Tilbage til albums",
                     slideshow: "Vis slideshow",
                     loading: "Henter billeder...",
                     page: "Side",
                     prev: "Forrige",
                     next: "Næste",
                     devider: "|"
            },
            months: ["Januar","Februar","Marts","April","Maj","Juni","Juli","August","September","Oktober","November","December"]
        });
    });
})(jQuery);', 'inline');
    return '<div id="picasaweb"></div>';
}
