<?php
/**
 * @file
 * Provides the ability to embed slideshows from Picasa Webalbums
 *
 * This module provides an input filter to add a slideshow from Picasa Webalbum anywhere
 * input filters are accepted. You have the option of replacing the filter tag
 * with a link to the scribd or embedding the scribd itself.
 */

/**
 * Implementation of hook_menu().
 */
function vih_picasaweb_slideshow_input_filter_menu() {
    $items = array();
    $items['admin/settings/picasawebalbum'] = array(
        'title' => 'VIH Picasa Webalbum',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('vih_picasaweb_slideshow_input_filter_admin_form'),
        'access arguments' => array('administer content types'),
        'type' => MENU_NORMAL_ITEM
    );
    return $items;
}

function vih_picasaweb_slideshow_input_filter_admin_form($form, &$form_state){
  $form['picasaweb_authkey'] = array(
    '#type' => 'textfield',
    '#title' => t('Picasaweb Auth Key'),
    '#required' => true,
    '#default_value' => variable_get('picasaweb_authkey'),
  );
  $form['picasaweb_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Picasaweb User'),
    '#required' => true,
    '#default_value' => variable_get('picasaweb_user'),
  ); 
  // saves and executes a submission callback, see $form["#submit"] for that
  $form['save'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#executes_submit_callback' => true
  );
  $form['#submit'] = array(
    'vih_picasaweb_slideshow_input_filter_admin_form_submit'
  );
  return $form;
}

function vih_picasaweb_slideshow_input_filter_admin_validate($form, &$form_state) {
}

function vih_picasaweb_slideshow_input_filter_admin_form_submit($form, &$form_state) {
  variable_set('picasaweb_authkey', $form_state['values']['picasaweb_authkey']);
  variable_set('picasaweb_user', $form_state['values']['picasaweb_user']);
  drupal_set_message(t("Values has been set"));
}

/**
 * Implementation of hook_filter_info().
 */
function vih_picasaweb_slideshow_input_filter_filter_info() {
  $filters['picasawebalbum_slideshow_filter'] = array(
    'title' => t('Picasa Webalbum Slideshow filter'),
    'description' => t('Substitutes [pws:xx] tags with the the slideshow located at https://picasaweb.google.com/xx/.'),
    'process callback'  => 'vih_picasaweb_slideshow_input_filter_filter_process',
    'default settings' => array(
      'vih_picasaweb_slideshow_input_filter_display_method' => 'embed',
    ),
    'settings callback' => 'vih_picasaweb_slideshow_input_filter_filter_settings',
    'tips callback' => 'vih_picasaweb_slideshow_input_filter_filter_tips',
    'cache' => TRUE,
  );
  return $filters;
}

/**
 * Process callback for hook_filter_info().
 */
function vih_picasaweb_slideshow_input_filter_filter_process($text, $filter, $format) {
  $display = $filter->settings['vih_picasaweb_slideshow_input_filter_display_method'];
  $callback = '_picasaweb_slideshow_display_' . $display;
  return preg_replace_callback('@\[pws\:(\d+)\:?(.*)?\]@', $callback, $text);
  
}

/**
 * Settings callback for vih_picasaweb_slideshow_input_filter
 */
function vih_picasaweb_slideshow_input_filter_filter_settings($form, $form_state, $filter, $format, $defaults) {
  $settings['picasaweb_filter_display_method'] = array(
    '#title' => t('Picasaweb Slideshow display method'),
    '#type' => 'select',
    '#options' => array(
      'embed' => t('Embed'),
      'link' => t('Link'),
    ),
    '#default_value' => isset($filter->settings['vih_picasaweb_slideshow_input_filter_display_method']) ? $filter->settings['vih_picasaweb_slideshow_input_filter_display_method'] : $defaults['vih_picasaweb_slideshow_input_filter_display_method'],
  );
  return $settings;
}

/**
 * Implements hook_filter_tips().
 */
function vih_picasaweb_slideshow_input_filter_filter_tips($filter, $format, $long = FALSE) {
  $display = $filter->settings['vih_picasaweb_slideshow_input_filter_display_method'];
  $action = $display == 'embed' ? t('embed the picasaweb slideshow') : t('create a link to the album');
  return t('Use [pws:xx] where xx is you album id to %action.', array('%action' => $action));
}

/**
 * Display a slideshow by replacing the text.
 */
function _picasaweb_slideshow_display_embed($matches) {
  $data['album_id'] = $matches[1];

  $output = array(
    '<embed type="application/x-shockwave-flash" src="https://picasaweb.google.com/s/c/bin/slideshow.swf" width="600" height="400" ' .
    'flashvars="host=picasaweb.google.com&captions=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F'.variable_get('picasaweb_user').'%2Falbumid%2F'.$data['album_id'].'%3Falt%3Drss%26kind%3Dphoto%26authkey%3'.variable_get('picasaweb_authkey').'%26hl%3Den_US" '. 
    'pluginspage="http://www.macromedia.com/go/getflashplayer">',
  );

  $output[] = '</embed>';

  return implode("\n", $output);
}

/**
 * Replace the text with a link.
 */
function _picasaweb_slideshow_display_link($matches) {
  $data['album_id'] = $matches[1];

  $picasaweb_url = 'https://picasaweb.google.com/' . $data['album_id'] . '/';
  return l($picasaweb_url, $picasaweb_url);
}

