<?php
/**
 * Redirects to legacy application
 */

/**
 * Implementation of hook_menu().
 */
function vih_redirect_menu() {
    $items = array();
    $items['login/%/%'] = array(
        'title' => 'Højdepunkter',
        'page callback' => '_vih_redirect',
        'page arguments' => array(1, 2),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
    );
    return $items;
}

function _vih_redirect($type, $key) {
    header('Location: http://tilmelding.vih.dk/login/' . $type . '/' . $key);
    exit;
}
