<?php

/**
 * Implements hook_menu().
 */
function vih_course_registration_long_menu() {
  $items = array();

  $items['registration/long/form'] = array(
    'title' => 'Register for long course',
    'page callback' => 'vih_course_registration_long_wizard',
    'access callback' => TRUE,
    'description' => 'Registration form',
    'file' => 'vih_course_registration_long.pages.inc',
  );

  return $items;
}

