<?php
/**
 * Integrates with Intraface newsletter
 */
set_include_path('/home/vih/pear/php/' . PATH_SEPARATOR . get_include_path());
require_once 'Ilib/ClassLoader.php';

/**
 * Implementation of hook_menu().
 */
function vih_newsletter_menu() {
  $items = array();
  $items['nyhedsbrev'] = array(
    'title' => 'Nyhedsbrev',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vih_newsletter_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu'
  );
  $items['admin/config/vih'] = array(
    'title' => 'VIH',
    'description' => 'Settings for Vejle Idrætshøjskoles custom modules.',
    'position' => 'right',
    'weight' => -5,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'vih_newsletter.admin.inc',
  );    
  $items['admin/system/vih'] = array(
    'title' => 'VIH Newsletter',
    'description' => 'Configure integration with Intraface Newsletter',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vih_newsletter_admin_form'),
    'access arguments' => array('administer permissions'),
    'file' => 'vih_newsletter.admin.inc'
  );
  return $items;
}

function vih_newsletter_form($form, &$form_state) {
  $form['newsletter'] = array(
    '#type' => 'fieldset', 
    '#title' => t('Newsletter'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );
  $form['newsletter']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
  );
  $form['newsletter']['email'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail'),
    '#required' => TRUE
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return system_settings_form($form);
}

function vih_newsletter_form_validate($form, &$form_state) {
  if (!valid_email_address($form_state['values']['email'])) {
     drupal_set_message(t('E-mail is not valid.'), 'error');
     return false;
  }
  return true;
}

function vih_newsletter_form_submit($form, &$form_state) {
  $credentials = array(
    "private_key" => variable_get('intraface_public_key'),
    "session_id"  => uniqid());
  XML_RPC2_Backend::setBackend("php"); 
  $client = new IntrafacePublic_Newsletter_Client_XMLRPC($credentials, variable_get('intraface_newsletter_list_id'));

  if ($client->subscribe($form_state['values']['email'], $form_state['values']['name'], $_SERVER['REMOTE_ADDR'])) {
    drupal_set_message(t('You are now subscribed to the newsletter with e-mail address @email', array('@email' => $form_state['values']['email'])));
  } else {
    drupal_set_message(t('Could not subscribe e-mail address @email', array('@email' => $form_state['values']['email']), 'error'));
  } 
}

