<?php
/**
 * Integrates with Intraface newsletter
 */
set_include_path('/home/vih/pear/php/' . PATH_SEPARATOR . get_include_path());
require_once 'Ilib/ClassLoader.php';

/**
 * Implementation of hook_menu().
 */
function vih_newsletter_menu() {
    $items = array();
    $items['nyhedsbrev'] = array(
        'title' => 'Nyhedsbrev',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('vih_newsletter_form'),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu'
    );
    $items['admin/settings/vih-newsletter'] = array(
        'title' => 'VIH Newsletter',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('vih_newsletter_admin_form'),
        'access arguments' => array('administer content types'),
        'type' => MENU_NORMAL_ITEM
    );
    return $items;
}

function vih_newsletter_form($form, &$form_state) {
  $form['newsletter'] = array(
    '#type' => 'fieldset', 
    '#title' => t('Newsletter'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );
  $form['newsletter']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
  );
  $form['newsletter']['email'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail'),
    '#required' => TRUE
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

function vih_newsletter_form_validate($form, &$form_state) {
  if (!valid_email_address($form_state['values']['email'])) {
     drupal_set_message(t('E-mail is not valid.'), 'error');
     return false;
  }
  return true;
}

function vih_newsletter_form_submit($form, &$form_state) {
  $credentials = array(
    "private_key" => variable_get('intraface_public_key'),
    "session_id"  => uniqid());
  XML_RPC2_Backend::setBackend("php"); 
  $client = new IntrafacePublic_Newsletter_Client_XMLRPC($credentials, variable_get('intraface_newsletter_list_id'));

  if ($client->subscribe($form_state['values']['email'], $form_state['values']['name'], $_SERVER['REMOTE_ADDR'])) {
    drupal_set_message(t('You are now subscribed to the newsletter with e-mail address @email', array('@email' => $form_state['values']['email'])));
  } else {
    drupal_set_message(t('Could not subscribe e-mail address @email', array('@email' => $form_state['values']['email']), 'error'));
  } 
}

function vih_newsletter_admin_form($form, &$form_state){
  $form['intraface_public_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Intraface Public Key'),
    '#required' => true,
    '#default_value' => variable_get('intraface_public_key'),
  );
  $form['intraface_newsletter_list_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Intraface Newsletter List ID'),
    '#required' => true,
    '#default_value' => variable_get('intraface_newsletter_list_id'),
  ); 
  // saves and executes a submission callback, see $form["#submit"] for that
  $form['save'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#executes_submit_callback' => true
  );
  $form['#submit'] = array(
    'vih_newsletter_admin_form_submit'
  );
  return $form;
}

function vih_newsletter_admin_validate($form, &$form_state) {
  $list_id = $form_state['values']['intraface_newsletter_list_id'];
  if (!is_numeric($list_id)) {
    form_set_error('intraface_newsletter_list_id', t('Intraface newsletter list ID must be numeric.'));
  }
}

function vih_newsletter_admin_form_submit($form, &$form_state) {
  variable_set('intraface_public_key', $form_state['values']['intraface_public_key']);
  variable_set('intraface_newsletter_list_id', $form_state['values']['intraface_newsletter_list_id']);
  drupal_set_message(t("Intraface values has been set"));
}

