<?php
function vih_course_short_menu() {
    $items = array();
    $items['kortekurser'] = array(
        'title' => 'Korte kurser',
        'page callback' => 'vih_course_short_view',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main_menu'
    );
    return $items;
}

function vih_course_short_load($id) {
    return $result = db_query("SELECT navn FROM {kortkursus} WHERE id = :id", array(':id' => $id), array('target' => 'vih'))->fetchObject();
}

function vih_course_short_view($id = 0) {
    if ($id > 0) {
        $course = vih_course_short_load($id);
        if (!$course) {
            // @todo
            drupal_add_http_header('Status', '404 Not Found');
            exit('404 / Page Not Found');
        }
        drupal_set_title($course->navn);
        return $course->navn;
    }
    drupal_set_title('Korte kurser');
    $courses = '';
    $result = db_query("SELECT navn FROM {kortkursus} WHERE dato_slut > :date", array(':date' => date('2009-m-d')), array('target' => 'vih'));
    
    // @todo HOWTO THEME THIS?
    foreach ($result as $course) {
        $courses .= $course->navn;
    }
    return $courses;
}
