<?php

/**
 * Implements hook_permission().
 */
function vih_brochures_permission() {
  return array(
    'mark brochure orders as sent' => array(
      'title' => t('Mark brochure orders as sent'),
    ),
    'view brochure orders' => array(
      'title' => t('View brochure orders'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vih_brochures_form_brochure_order_node_form_alter(&$form, &$form_state, $form_id) {
  $form['field_brochure_sent']['#access'] = user_access('mark brochure orders as sent');
}

include_once('vih_brochures.features.inc');
